site_name: CalcpadCE Documentation
use_directory_urls: false

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - content.code.copy

hooks:
  - hooks/math_fix.py

nav:
  - Home:
    - index.md
    - Fields of Application: fields-of-application.md
    - Installation: installation.md
    - Licensing: licensing-and-terms-of-use.md
    - How It Works: how-it-works.md
    - Theoretical Background: theoretical-background.md
    - Writing Math: writing-math.md
    - Reporting: reporting.md
    - Programming: programming.md
    - Results: results.md
    - Working with Files: working-with-files.md
  - Expressions:
    - expressions/index.md
    - Constants: expressions/constants.md
    - Variables: expressions/variables.md
    - Operators: expressions/operators.md
    - Brackets: expressions/brackets.md
    - Functions: expressions/functions.md
    - Plotting: expressions/plotting.md
    - Numerical Methods: expressions/numerical-methods.md
    - Iterative Procedures: expressions/iterative-procedures.md
    - Units: expressions/units.md
    - Vectors: expressions/vectors.md
    - Matrices: expressions/matrices.md
    - High Performance Vectors and Matrices: expressions/high-performance-vectors-and-matrices.md

markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/object/apply:pymdownx.arithmatex.arithmatex_fenced_format
            kwds:
              mode: generic

extra_javascript:
  - javascripts/mathjax.js
  - javascripts/mathjax/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css
